spring.application.name=twitter

spring.cloud.aws.credentials.access-key=accessKey
spring.cloud.aws.credentials.secret-key=secret
spring.cloud.aws.region.static=us-east-2

aws.s3.bucket-name=twitter-storage-bucket-307869382024-us-east-2-an
spring.cloud.aws.credentials.profile.name=springboot-s3-user